services:
  imaotai-db:
    image: mysql:8.0.35
    container_name: imaotai-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - ./volumes/db/data/:/var/lib/mysql/
      - ./volumes/db/logs:/logs
      - ./doc/sql/campus_imaotai-1.0.5.sql:/docker-entrypoint-initdb.d/campus_imaotai-1.0.5.sql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1',
          '--default-authentication-plugin=mysql_native_password'
        ]
    networks:
      - imaotai_net
    restart: always

  imaotai-redis:
    image: redis:6.2.12
    container_name: imaotai-redis
    volumes:
      - ./volumes/redis/data/:/redis/data/
    networks:
      - imaotai_net
    restart: always

  imaotai-api:
    image: imaotai-api:latest
    build:
      context: .
      dockerfile: ./api.Dockerfile
    container_name: imaotai-api
    volumes:
      - ./templates/application-prod.yml:/app/application-prod.yml
    networks:
      - imaotai_net
    depends_on:
      - imaotai-db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8160/captchaImage"]
      interval: 3s
      timeout: 10s
      retries: 20
      start_period: 40s
      start_interval: 5s

  imaotai-web:
    image: imaotai-web:latest
    build:
      context: .
      dockerfile: ./web.Dockerfile
    container_name: imaotai-web
    volumes:
      - ./templates/web.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/web/log:/var/log/nginx
    privileged: true
    networks:
      - imaotai_net
    ports:
      - 80:80
    depends_on:
      imaotai-api:
        restart: false
        condition: service_healthy
    restart: always

networks:
  imaotai_net:
    name: imaotai_net